### ISSUE TITLE
Multiple issues on initial install

### ISSUE THREAD

**Issue by seriph** [horizon-ui/horizon-ui-chakra-pro-nextjs#2]
Simply installed via yarn install, yarn dev and received multiple issues/warnings in the terminal and UI:

Issue 1 in UI:
Unhandled Runtime Error
Error: Hydration failed because the initial UI does not match what was rendered on the server.

See more info here: https://nextjs.org/docs/messages/react-hydration-error

Issue 2 in Terminal:
Warning: Portal: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
    at Portal (webpack-internal:///(sc_client)/./node_modules/@chakra-ui/portal/dist/chakra-ui-portal.cjs.dev.js:195:28)
    at div
    at eval (webpack-internal:///(sc_client)/./node_modules/@emotion/react/dist/emotion-element-3838ba9e.esm.js:67:68)
    at div
    at eval (webpack-internal:///(sc_client)/./node_modules/@emotion/react/dist/emotion-element-3838ba9e.esm.js:67:68)

**Comment by seriph** [comment]
Here is the full install:

$ yarn install
yarn install v1.22.19
[1/4] Resolving packages...
warning Resolution field "@types/react@17.0.2" is incompatible with requested version "@types/react@^17.0.15"
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @asseinfo/react-kanban@2.2.0" has incorrect peer dependency "react@^16.8.0 || ^17.0.0".
warning " > @asseinfo/react-kanban@2.2.0" has incorrect peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning " > @babel/preset-react@7.18.6" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-react > @babel/plugin-transform-react-display-name@7.18.6" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-react > @babel/plugin-transform-react-jsx@7.21.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-react > @babel/plugin-transform-react-jsx-development@7.18.6" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-react > @babel/plugin-transform-react-pure-annotations@7.18.6" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-react > @babel/plugin-transform-react-jsx > @babel/plugin-syntax-jsx@7.18.6" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@chakra-ui/react > @chakra-ui/modal > react-remove-scroll@2.4.1" has incorrect peer dependency "react@^16.8.0 || ^17.0.0".
warning "@chakra-ui/react > @chakra-ui/toast > @reach/alert@0.13.2" has incorrect peer dependency "react@^16.8.0 || 17.x".
warning "@chakra-ui/react > @chakra-ui/toast > @reach/alert@0.13.2" has incorrect peer dependency "react-dom@^16.8.0 || 17.x".
warning "@chakra-ui/react > @chakra-ui/modal > @chakra-ui/focus-lock > react-focus-lock@2.5.2" has incorrect peer dependency "react@^16.8.0 || ^17.0.0".
warning "@chakra-ui/react > @chakra-ui/toast > @reach/alert > @reach/utils@0.13.2" has incorrect peer dependency "react@^16.8.0 || 17.x".
warning "@chakra-ui/react > @chakra-ui/toast > @reach/alert > @reach/utils@0.13.2" has incorrect peer dependency "react-dom@^16.8.0 || 17.x".
warning "@chakra-ui/react > @chakra-ui/toast > @reach/alert > @reach/visually-hidden@0.13.2" has incorrect peer dependency "react@^16.8.0 || 17.x".
warning "@chakra-ui/react > @chakra-ui/toast > @reach/alert > @reach/visually-hidden@0.13.2" has incorrect peer dependency "react-dom@^16.8.0 || 17.x".
warning " > @fullcalendar/react@5.9.0" has incorrect peer dependency "react@^16.7.0 || ^17".
warning " > @fullcalendar/react@5.9.0" has incorrect peer dependency "react-dom@^16.7.0 || ^17".
warning " > @testing-library/user-event@12.8.3" has unmet peer dependency "@testing-library/dom@>=7.21.4".
warning " > css-loader@6.7.3" has unmet peer dependency "webpack@^5.0.0".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 5.00s.
$ yarn install
yarn install v1.22.19
[1/4] Resolving packages...
warning Resolution field "@types/react@17.0.2" is incompatible with requested version "@types/react@^17.0.15"
success Already up-to-date.
Done in 0.25s.
$ yarn dev
yarn run v1.22.19
$ next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
warn  - You have enabled experimental feature (appDir) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

info  - Thank you for testing `appDir` please leave your feedback at https://nextjs.link/app-feedback
event - compiled client and server successfully in 1178 ms (261 modules)
wait  - compiling...
event - compiled client and server successfully in 261 ms (261 modules)
wait  - compiling /admin/dashboards/default/page (client and server)...
event - compiled client and server successfully in 2.5s (1533 modules)
`head.js` is being used in route /. Please migrate to the Metadata API for an improved experience: https://beta.nextjs.org/docs/api-reference/metadata
Warning: ChakraProvider: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
    at ChakraProvider (webpack-internal:///(sc_client)/./node_modules/@chakra-ui/provider/dist/chakra-ui-provider.cjs.dev.js:40:24)
    at AppWrappers (webpack-internal:///(sc_client)/./src/app/AppWrappers.tsx:24:24)
    at Lazy
    at body
    at html
    at ReactDevOverlay (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/react-dev-overlay/internal/ReactDevOverlay.js:61:9)
    at HotReload (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/react-dev-overlay/hot-reloader-client.js:19:22)
    at Router (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/app-router.js:45:23)
    at ErrorBoundaryHandler (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/error-boundary.js:57:9)
    at ErrorBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/error-boundary.js:69:26)
    at AppRouter (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/app-router.js:23:13)
    at Lazy
    at Lazy
    at ServerComponentWrapper (/home/serif/Hawken/attain/attain-gateway-ui/node_modules/next/dist/server/app-render.js:305:28)
    at ServerComponentWrapper (/home/serif/Hawken/attain/attain-gateway-ui/node_modules/next/dist/server/app-render.js:305:28)
    at InsertedHTML (/home/serif/Hawken/attain/attain-gateway-ui/node_modules/next/dist/server/app-render.js:1173:33)
Image with src "/_next/static/media/avatar4.7b667880.png" has legacy prop "layout". Did you forget to run the codemod?
Read more: https://nextjs.org/docs/messages/next-image-upgrade-to-13
Image with src "/_next/static/media/avatar4.7b667880.png" has legacy prop "objectFit". Did you forget to run the codemod?
Read more: https://nextjs.org/docs/messages/next-image-upgrade-to-13
Warning: Portal: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
    at Portal (webpack-internal:///(sc_client)/./node_modules/@chakra-ui/portal/dist/chakra-ui-portal.cjs.dev.js:195:28)
    at div
    at eval (webpack-internal:///(sc_client)/./node_modules/@emotion/react/dist/emotion-element-3838ba9e.esm.js:67:68)
    at div
    at eval (webpack-internal:///(sc_client)/./node_modules/@emotion/react/dist/emotion-element-3838ba9e.esm.js:67:68)
    at AdminLayout (webpack-internal:///(sc_client)/./src/app/admin/layout.tsx:32:24)
    at Lazy
    at ScrollAndFocusHandler (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:145:1)
    at InnerLayoutRouter (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:186:30)
    at RedirectErrorBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:343:9)
    at RedirectBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:349:29)
    at NotFoundErrorBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:375:9)
    at NotFoundBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:381:29)
    at LoadingBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:304:32)
    at ErrorBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/error-boundary.js:69:26)
    at RenderFromTemplateContext (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/render-from-template-context.js:10:34)
    at Lazy
    at OuterLayoutRouter (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/layout-router.js:21:30)
    at Lazy
    at EnvironmentProvider (webpack-internal:///(sc_client)/./node_modules/@chakra-ui/react-env/dist/chakra-ui-react-env.cjs.dev.js:120:24)
    at ColorModeProvider (webpack-internal:///(sc_client)/./node_modules/@chakra-ui/color-mode/dist/chakra-ui-color-mode.cjs.dev.js:228:21)
    at ThemeProvider (webpack-internal:///(sc_client)/./node_modules/@emotion/react/dist/emotion-element-3838ba9e.esm.js:122:64)
    at ThemeProvider (webpack-internal:///(sc_client)/./node_modules/@chakra-ui/system/dist/chakra-ui-system.cjs.dev.js:57:27)
    at eval (webpack-internal:///(sc_client)/./node_modules/@chakra-ui/hooks/dist/chakra-ui-hooks.cjs.dev.js:265:23)
    at ChakraProvider (webpack-internal:///(sc_client)/./node_modules/@chakra-ui/provider/dist/chakra-ui-provider.cjs.dev.js:40:24)
    at AppWrappers (webpack-internal:///(sc_client)/./src/app/AppWrappers.tsx:24:24)
    at Lazy
    at body
    at html
    at ReactDevOverlay (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/react-dev-overlay/internal/ReactDevOverlay.js:61:9)
    at HotReload (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/react-dev-overlay/hot-reloader-client.js:19:22)
    at Router (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/app-router.js:45:23)
    at ErrorBoundaryHandler (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/error-boundary.js:57:9)
    at ErrorBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/error-boundary.js:69:26)
    at AppRouter (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/app-router.js:23:13)
    at Lazy
    at Lazy
    at ServerComponentWrapper (/home/serif/Hawken/attain/attain-gateway-ui/node_modules/next/dist/server/app-render.js:305:28)
    at ServerComponentWrapper (/home/serif/Hawken/attain/attain-gateway-ui/node_modules/next/dist/server/app-render.js:305:28)
    at InsertedHTML (/home/serif/Hawken/attain/attain-gateway-ui/node_modules/next/dist/server/app-render.js:1173:33)
Image with src "/_next/static/media/fakeGraph.c170f6ce.png" has legacy prop "layout". Did you forget to run the codemod?
Read more: https://nextjs.org/docs/messages/next-image-upgrade-to-13
Image with src "/_next/static/media/fakeGraph.c170f6ce.png" has legacy prop "objectFit". Did you forget to run the codemod?
Read more: https://nextjs.org/docs/messages/next-image-upgrade-to-13
Image with src "/_next/static/media/avatar1.0a2b6004.png" has legacy prop "layout". Did you forget to run the codemod?
Read more: https://nextjs.org/docs/messages/next-image-upgrade-to-13
Image with src "/_next/static/media/avatar1.0a2b6004.png" has legacy prop "objectFit". Did you forget to run the codemod?
Read more: https://nextjs.org/docs/messages/next-image-upgrade-to-13
Image with src "/_next/static/media/avatar2.af6a0c88.png" has legacy prop "layout". Did you forget to run the codemod?
Read more: https://nextjs.org/docs/messages/next-image-upgrade-to-13
Image with src "/_next/static/media/avatar2.af6a0c88.png" has legacy prop "objectFit". Did you forget to run the codemod?
Read more: https://nextjs.org/docs/messages/next-image-upgrade-to-13
Image with src "/_next/static/media/avatar3.92c62482.png" has legacy prop "layout". Did you forget to run the codemod?
Read more: https://nextjs.org/docs/messages/next-image-upgrade-to-13
Image with src "/_next/static/media/avatar3.92c62482.png" has legacy prop "objectFit". Did you forget to run the codemod?
Read more: https://nextjs.org/docs/messages/next-image-upgrade-to-13
Creating Table Instance...
⏱     1 /    1 ms getRowModel
⏱     0 /    1 ms getSortedRowModel
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 444 ms (1534 modules)

**Comment by seriph** [comment]
<img width="1901" alt="logs" src="https://user-images.githubusercontent.com/1385955/225161187-11db93ff-3901-4c32-8f0e-d4417f26b4c7.png">

**Comment by simmmpleweb** [comment]
Hello, @seriph ! Thanks for supporting Horizon! This issue was solved in the latest release. If you have anymore questions feel free to ask! 
Regards, Vlad.
